In [1]:
#import mudules
import numpy as np
import pandas as pd

In [2]:
# Read data
nf1_data = pd.read_csv("NFL Play by Play 2009-2017 (v4).csv")

C:\Users\Data\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (25,51) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [3]:
#Set seed for reproducibility
np.random.seed(0)

In [4]:
nf1_data.shape

(407688, 102)

In [5]:
# Looking and the first five rows of the nf1_data file
nf1_data.head()

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2009-09-10,2009091000,1,1,NaN,15:00,15,3600.0,0.0,TEN,...,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009
1,2009-09-10,2009091000,1,1,1.0,14:53,15,3593.0,7.0,PIT,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,2009-09-10,2009091000,1,1,2.0,14:16,15,3556.0,37.0,PIT,...,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009
3,2009-09-10,2009091000,1,1,3.0,13:35,14,3515.0,41.0,PIT,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2009-09-10,2009091000,1,1,4.0,13:27,14,3507.0,8.0,PIT,...,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009

In [6]:
# Get the number of missing data points per column
missing_values_count = nf1_data.isnull().sum()

In [7]:
# missing values
total_cells = np.product(nf1_data.shape)
total_missing = missing_values_count.sum()

#percentage
percent_missing = (total_missing / total_cells) * 100
print(percent_missing)

24.87214126835169

In [8]:
missing_values_count[:50]

Date                       0
GameID                     0
Drive                      0
qtr                        0
down                   61154
time                     224
TimeUnder                  0
TimeSecs                 224
PlayTimeDiff             444
SideofField              528
yrdln                    840
yrdline100               840
ydstogo                    0
ydsnet                     0
GoalToGo                 840
FirstDown              28811
posteam                24992
DefensiveTeam          24992
desc                       2
PlayAttempted              0
Yards.Gained               0
sp                         0
Touchdown                  0
ExPointResult         397578
TwoPointConv          407083
DefTwoPoint           407664
Safety                     0
Onsidekick                 0
PuntResult            385317
PlayType                   0
Passer                240045
Passer_ID                  0
PassAttempt                0
PassOutcome           239506
PassLength            240520
AirYards                   0
YardsAfterCatch            0
QBHit                      0
PassLocation          240520
InterceptionThrown         0
Interceptor           403168
Rusher                287124
Rusher_ID                  0
RushAttempt                0
RunLocation           288178
RunGap                320260
Receiver              246127
Receiver_ID                0
Reception                  0
ReturnResult          389450
dtype: int64

In [9]:
missing_values_count[50:]

Returner                       382384
BlockingPlayer                 407571
Tackler1                       166134
Tackler2                       357953
FieldGoalResult                398629
FieldGoalDistance              398740
Fumble                              0
RecFumbTeam                    403315
RecFumbPlayer                  403315
Sack                                0
Challenge.Replay                    0
ChalReplayResult               404286
Accepted.Penalty                    0
PenalizedTeam                  378189
PenaltyType                    391261
PenalizedPlayer                379403
Penalty.Yards                       0
PosTeamScore                    26904
DefTeamScore                    26904
ScoreDiff                       24988
AbsScoreDiff                    26904
HomeTeam                            0
AwayTeam                            0
Timeout_Indicator                   0
Timeout_Team                        0
posteam_timeouts_pre                0
HomeTimeouts_Remaining_Pre          0
AwayTimeouts_Remaining_Pre          0
HomeTimeouts_Remaining_Post         0
AwayTimeouts_Remaining_Post         0
No_Score_Prob                     176
Opp_Field_Goal_Prob               176
Opp_Safety_Prob                   176
Opp_Touchdown_Prob                176
Field_Goal_Prob                   176
Safety_Prob                       176
Touchdown_Prob                    176
ExPoint_Prob                        0
TwoPoint_Prob                       0
ExpPts                            176
EPA                               369
airEPA                         248394
yacEPA                         248498
Home_WP_pre                     24954
Away_WP_pre                     24954
Home_WP_post                    26587
Away_WP_post                    26587
Win_Prob                        25009
WPA                              5541
airWPA                         248501
yacWPA                         248762
Season                              0
dtype: int64

### 1. Drop missing values
not recommended, bacause we may lose some useful information

In [10]:
nf1_data.dropna()

Empty DataFrame
Columns: [Date, GameID, Drive, qtr, down, time, TimeUnder, TimeSecs, PlayTimeDiff, SideofField, yrdln, yrdline100, ydstogo, ydsnet, GoalToGo, FirstDown, posteam, DefensiveTeam, desc, PlayAttempted, Yards.Gained, sp, Touchdown, ExPointResult, TwoPointConv, DefTwoPoint, Safety, Onsidekick, PuntResult, PlayType, Passer, Passer_ID, PassAttempt, PassOutcome, PassLength, AirYards, YardsAfterCatch, QBHit, PassLocation, InterceptionThrown, Interceptor, Rusher, Rusher_ID, RushAttempt, RunLocation, RunGap, Receiver, Receiver_ID, Reception, ReturnResult, Returner, BlockingPlayer, Tackler1, Tackler2, FieldGoalResult, FieldGoalDistance, Fumble, RecFumbTeam, RecFumbPlayer, Sack, Challenge.Replay, ChalReplayResult, Accepted.Penalty, PenalizedTeam, PenaltyType, PenalizedPlayer, Penalty.Yards, PosTeamScore, DefTeamScore, ScoreDiff, AbsScoreDiff, HomeTeam, AwayTeam, Timeout_Indicator, Timeout_Team, posteam_timeouts_pre, HomeTimeouts_Remaining_Pre, AwayTimeouts_Remaining_Pre, HomeTimeouts_Remaining_Post, AwayTimeouts_Remaining_Post, No_Score_Prob, Opp_Field_Goal_Prob, Opp_Safety_Prob, Opp_Touchdown_Prob, Field_Goal_Prob, Safety_Prob, Touchdown_Prob, ExPoint_Prob, TwoPoint_Prob, ExpPts, EPA, airEPA, yacEPA, Home_WP_pre, Away_WP_pre, Home_WP_post, Away_WP_post, Win_Prob, WPA, airWPA, ...]
Index: []

[0 rows x 102 columns]

All the data is removed because every row in the dataset has at least one missing value.

So, we need to remove only columns that have at least one missing value

In [11]:
# We will specify the columns only by setting the `axis` parameter to `1`
columns_with_na_dropped = nf1_data.dropna(axis = 1)
columns_with_na_dropped.head()

,Date,GameID,Drive,qtr,TimeUnder,ydstogo,ydsnet,PlayAttempted,Yards.Gained,sp,...,Timeout_Indicator,Timeout_Team,posteam_timeouts_pre,HomeTimeouts_Remaining_Pre,AwayTimeouts_Remaining_Pre,HomeTimeouts_Remaining_Post,AwayTimeouts_Remaining_Post,ExPoint_Prob,TwoPoint_Prob,Season
0,2009-09-10,2009091000,1,1,15,0,0,1,39,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
1,2009-09-10,2009091000,1,1,15,10,5,1,5,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
2,2009-09-10,2009091000,1,1,15,5,2,1,-3,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
3,2009-09-10,2009091000,1,1,14,8,2,1,0,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
4,2009-09-10,2009091000,1,1,14,8,2,1,0,0,...,0,None,3,3,3,3,3,0.0,0.0,2009

In [12]:
# How much data did we lose?
print("Columns in original dataset: %d \n" %nf1_data.shape[1])
print("Columns in na's dropped dataset: %d \n" %columns_with_na_dropped.shape[1])

Columns in original dataset: 102

Columns in na's dropped dataset: 41

We lost much data by applying this approach, so this is not recommended

In [13]:
nf1_data.head()

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2009-09-10,2009091000,1,1,NaN,15:00,15,3600.0,0.0,TEN,...,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009
1,2009-09-10,2009091000,1,1,1.0,14:53,15,3593.0,7.0,PIT,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,2009-09-10,2009091000,1,1,2.0,14:16,15,3556.0,37.0,PIT,...,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009
3,2009-09-10,2009091000,1,1,3.0,13:35,14,3515.0,41.0,PIT,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2009-09-10,2009091000,1,1,4.0,13:27,14,3507.0,8.0,PIT,...,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009

### 2. Filling in missing values automatically
We use `fillna` method to sill NaN values in the dataset automatically. We pass an argument to it to specify the value we want to replace the NaN values with

In [14]:
# Replace all NaN values with 0
nf1_data.fillna(0).head(6)

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2009-09-10,2009091000,1,1,0.0,15:00,15,3600.0,0.0,TEN,...,0.000000,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,0.000000,0.000000,2009
1,2009-09-10,2009091000,1,1,1.0,14:53,15,3593.0,7.0,PIT,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,2009-09-10,2009091000,1,1,2.0,14:16,15,3556.0,37.0,PIT,...,0.000000,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,0.000000,0.000000,2009
3,2009-09-10,2009091000,1,1,3.0,13:35,14,3515.0,41.0,PIT,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2009-09-10,2009091000,1,1,4.0,13:27,14,3507.0,8.0,PIT,...,0.000000,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,0.000000,0.000000,2009
5,2009-09-10,2009091000,2,1,1.0,13:16,14,3496.0,11.0,TEN,...,0.000000,0.558929,0.441071,0.578453,0.421547,0.441071,-0.019524,0.000000,0.000000,2009

We also can replace all NA's values with the value that comes directly after it in the same column by passin the value `bfill` to the `method` argument of the `fillna` method

In [15]:
# then replace all the remaining na's with 0
nf1_data.fillna(method = 'bfill', axis = 0).head(10).fillna(0)

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2009-09-10,2009091000,1,1,1.0,15:00,15,3600.0,0.0,TEN,...,1.146076,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,-0.032244,0.036899,2009
1,2009-09-10,2009091000,1,1,1.0,14:53,15,3593.0,7.0,PIT,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,2009-09-10,2009091000,1,1,2.0,14:16,15,3556.0,37.0,PIT,...,-5.031425,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,0.106663,-0.156239,2009
3,2009-09-10,2009091000,1,1,3.0,13:35,14,3515.0,41.0,PIT,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2009-09-10,2009091000,1,1,4.0,13:27,14,3507.0,8.0,PIT,...,0.163935,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,-0.010456,0.006029,2009
5,2009-09-10,2009091000,2,1,1.0,13:16,14,3496.0,11.0,TEN,...,0.163935,0.558929,0.441071,0.578453,0.421547,0.441071,-0.019524,-0.010456,0.006029,2009
6,2009-09-10,2009091000,2,1,2.0,12:40,13,3460.0,36.0,TEN,...,0.163935,0.578453,0.421547,0.582881,0.417119,0.421547,-0.004427,-0.010456,0.006029,2009
7,2009-09-10,2009091000,2,1,3.0,12:11,13,3431.0,29.0,TEN,...,0.541602,0.582881,0.417119,0.617544,0.382456,0.417119,-0.034663,-0.024526,0.018442,2009
8,2009-09-10,2009091000,2,1,4.0,11:34,12,3394.0,37.0,TEN,...,0.541602,0.617544,0.382456,0.591489,0.408511,0.382456,0.026054,-0.024526,0.018442,2009
9,2009-09-10,2009091000,3,1,1.0,11:24,12,3384.0,10.0,TEN,...,0.541602,0.591489,0.408511,0.585405,0.414595,0.591489,-0.006084,-0.024526,0.018442,2009